version: "3.9"

services:

  reverse-proxy:
    image: traefik:v2.7
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yaml:/traefik.yaml
      - ./traefik.log:/traefik.log

  develop:
    build: .
    restart: always
    labels:
      - traefik.http.routers.develop.rule=Host(`develop.cristianalvarezh.com`)
    depends_on:
      - reverse-proxy
