name: CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [opened, synchronize, closed]

jobs:

  deploy:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-20.04
    steps:
      - uses: tzzs/server-shell@v3
        with:
          PRIVATE_KEY: ${{secrets.PRIVATE_KEY}}
          USERNAME: ${{secrets.USERNAME}}
          IP: ${{secrets.IP}}
          PORT: 22
          SHELL: |
            "cd /home/ec2-user/github-actions-cicd && make refresh"

  temp-staging:
    if: github.event_name == 'pull_request' && github.event.action != 'closed' && github.event.action != 'synchronize'
    runs-on: ubuntu-20.04
    steps:
      - uses: tzzs/server-shell@v3
        with:
          PRIVATE_KEY: ${{secrets.PRIVATE_KEY}}
          USERNAME: ${{secrets.USERNAME}}
          IP: ${{secrets.IP}}
          PORT: 22
          SHELL: |
            "cd /home/ec2-user/github-actions-cicd && make temp-staging commit=$(echo ${{github.event.pull_request.head.sha}} | cut -c -7)"

  rm-temp-staging:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-20.04
    steps:
      - uses: tzzs/server-shell@v3
        with:
          PRIVATE_KEY: ${{secrets.PRIVATE_KEY}}
          USERNAME: ${{secrets.USERNAME}}
          IP: ${{secrets.IP}}
          PORT: 22
          SHELL: |
            "cd /home/ec2-user/github-actions-cicd && make rm-temp-staging commit=$(echo ${{github.event.pull_request.head.sha}} | cut -c -7)"
